--#SET TERMINATOR ;

-- =============================================
-- Application: Sample 01 - Basic SaveToDB Features
-- Version 10.8, January 9, 2023
--
-- Copyright 2012-2023 Gartle LLC
--
-- License: MIT
-- =============================================

DROP PROCEDURE  S01.USP_CASH_BY_MONTHS;
DROP PROCEDURE  S01.USP_CASH_BY_MONTHS_CHANGE;

DROP PROCEDURE  S01.USP_CASHBOOK;
DROP PROCEDURE  S01.USP_CASHBOOK2;
DROP PROCEDURE  S01.USP_CASHBOOK3;
DROP PROCEDURE  S01.USP_CASHBOOK4;
DROP PROCEDURE  S01.USP_CASHBOOK2_INSERT;
DROP PROCEDURE  S01.USP_CASHBOOK2_UPDATE;
DROP PROCEDURE  S01.USP_CASHBOOK2_DELETE;
DROP PROCEDURE  S01.USP_CASHBOOK3_CHANGE;
DROP PROCEDURE  S01.USP_CASHBOOK4_MERGE;

DROP VIEW       S01.VIEW_CASHBOOK;

DROP TABLE      S01.CASHBOOK;
DROP TABLE      S01.FORMATS;
DROP TABLE      S01.WORKBOOKS;

DROP SCHEMA     S01 RESTRICT;

echo Application removed
