--#SET TERMINATOR ;

-- =============================================
-- Application: Sample 13 - Tests
-- Version 10.13, April 29, 2024
--
-- Copyright 2021-2024 Gartle LLC
--
-- License: MIT
-- =============================================

GRANT SELECT, INSERT, UPDATE, DELETE ON S13.DATATYPES       TO SAMPLE13_USER1;
GRANT SELECT, INSERT, UPDATE, DELETE ON S13.QUOTES          TO SAMPLE13_USER1;

GRANT SELECT ON S13.VIEW_DATATYPE_COLUMNS                   TO SAMPLE13_USER1;
GRANT SELECT ON S13.VIEW_DATATYPE_PARAMETERS                TO SAMPLE13_USER1;

GRANT EXECUTE ON PROCEDURE S13.USP_DATATYPES                TO SAMPLE13_USER1;
GRANT EXECUTE ON PROCEDURE S13.USP_DATATYPES_DELETE         TO SAMPLE13_USER1;
GRANT EXECUTE ON PROCEDURE S13.USP_DATATYPES_INSERT         TO SAMPLE13_USER1;
GRANT EXECUTE ON PROCEDURE S13.USP_DATATYPES_UPDATE         TO SAMPLE13_USER1;

GRANT EXECUTE ON PROCEDURE S13.USP_ODBC_DATATYPES           TO SAMPLE13_USER1;
GRANT EXECUTE ON PROCEDURE S13.USP_ODBC_DATATYPES_DELETE    TO SAMPLE13_USER1;
GRANT EXECUTE ON PROCEDURE S13.USP_ODBC_DATATYPES_INSERT    TO SAMPLE13_USER1;
GRANT EXECUTE ON PROCEDURE S13.USP_ODBC_DATATYPES_UPDATE    TO SAMPLE13_USER1;

GRANT EXECUTE ON PROCEDURE S13.USP_QUOTES                   TO SAMPLE13_USER1;
GRANT EXECUTE ON PROCEDURE S13.USP_QUOTES_DELETE            TO SAMPLE13_USER1;
GRANT EXECUTE ON PROCEDURE S13.USP_QUOTES_INSERT            TO SAMPLE13_USER1;
GRANT EXECUTE ON PROCEDURE S13.USP_QUOTES_UPDATE            TO SAMPLE13_USER1;
