--#SET TERMINATOR ;

-- =============================================
-- Application: Sample 13 - Tests
-- Version 10.6, December 13, 2022
--
-- Copyright 2021-2022 Gartle LLC
--
-- License: MIT
-- =============================================

DROP PROCEDURE S13.USP_DATATYPES;
DROP PROCEDURE S13.USP_DATATYPES_DELETE;
DROP PROCEDURE S13.USP_DATATYPES_INSERT;
DROP PROCEDURE S13.USP_DATATYPES_UPDATE;

DROP PROCEDURE S13.USP_ODBC_DATATYPES;
DROP PROCEDURE S13.USP_ODBC_DATATYPES_DELETE;
DROP PROCEDURE S13.USP_ODBC_DATATYPES_INSERT;
DROP PROCEDURE S13.USP_ODBC_DATATYPES_UPDATE;

DROP PROCEDURE S13.USP_QUOTES;
DROP PROCEDURE S13.USP_QUOTES_DELETE;
DROP PROCEDURE S13.USP_QUOTES_INSERT;
DROP PROCEDURE S13.USP_QUOTES_UPDATE;

DROP VIEW S13.VIEW_DATATYPE_PARAMETERS;
DROP VIEW S13.VIEW_DATATYPE_COLUMNS;

DROP TABLE S13.DATATYPES;
DROP TABLE S13.QUOTES;

DROP SCHEMA S13 RESTRICT;

echo Application removed
